# Configuration for pyLINEAR (Oct. 11, 2019)

cpu: &CPU
  ncpu: 1                                # number of processors to use
  verbose: true

calib: &CALIB
  h5conf: hst_wfc3_ir_beams.h5           # HDF5 file for beam info
  h5flat: null                           # HDF5 file for flat field
  h5siaf: hst_wfc3_ir_detector.h5        # HDF5 file for detectors
    
tables: &TABLES
  path: TABLES2/                         # relative path for the tables
  remake: true                           # force to remake the tables
  gzip: true                             # gzip the resulting data
  nsub: 5                                # num intervals for trap. integrate
  cpu: *CPU                              # import CPU settings
  
sources:
  segmap: seg.fits                       # segmentation map for sources
  obslst: obs.lst                        # file describing the bands
  detindex: 0                            # detection index in obslst
  maglim: 26.                            # magnitude limit of sources
  minpix: 5                              # minimum number of pixels
  filtsig: 0                             # sigma of Gaussian filter
  eroderad: 0                            # num of pix to remove on outer edge
  binfact: 0                             # num of pix to block ave over
  
modules:
  simulation:
    perform: false                       # flag to run the simulation
    beam: A                              # beams to simulate
    grism: G102                          # which grism to simulate
    imgtype: wcs                         # where WCS comes from: wcs or img
    gzip: true                           # gzip the outputs
    imglst: wcs.lst                      # list of WCS properties
    sedlst: sed.lst                      # list of SEDs
    noise:                               # the noise module
      perform: false                     # flag to perform noise calculation
      exptime: 700.                      # effective exposure time
      skyrate: 0.3                       # background rate in e/s
    cpu: *CPU                            # import CPU settings
    calib: *CALIB                        # import calibration settings
    tables: *TABLES                      # import Tables settings

  extraction:
    perform: true 
    mode: golden
    group: True
    logdamp: [-6.,-1.,0.1]
    outroot: test
    imglst: flt.lst
    beam: A
    mask: null
    lamb0: null
    lamb1: null
    dlamb: null
    initialize: 'broadband'
    lsqr:
      atol: 1e-10          # a tol
      btol: 1e-10
      conlim: 1e10
      maxiter: 1e5
      show: False
    cpu: *CPU
    calib: *CALIB
    tables: *TABLES
    mcmcunc:
      perform: false
      nwalkers: 100
      nstep: 100
      burn: 0.2
      cpu: *CPU
    residuals:
      perform: true
      gzip: false
          
  cutout:
    perform: false
    beam: A
    #grism: G102
    imglst: flt.lst
    padding: [0,2]
    cpu: *CPU
    calib: *CALIB

